import { skills as s } from "./skills";
import { StaticImageData } from "next/image";
import memories from "../../public/memories.webp";
import appleStore from "../../public/apple_like_store.webp";
import autoCorrection from "../../public/auto_correction_smart_examination_system.webp";
import portfolio from "../../public/portfolio.webp";
import proShop from "../../public/proShop.webp";
import globe from "../../public/globe.webp";
import platformer from "../../public/platformer.webp";

export interface ProjectType {
  title: string;
  description: string;
  year: number;
  isOriginal?: boolean;
  demoSrc?: string;
  repoSrc?: string;
  imgSrc: StaticImageData | string;
  imgAlt: string;
  skills: string[];
}

export const projects: ProjectType[] = [
  {
    title: "Portfolio",
    description:
      "One of my top priorities was developing an accessible portfolio for all users, regardless of any visual limitations they may have. To achieve this goal, I have used color schemes that are friendly for those who are colorblind, and I have made sure to be in compliance with WCAG standards. Utilizing the latest features of Next.js 13 and Native CSS, I have brought my vision to life with a minimalist design that sets my work apart from others.",
    year: 2023,
    isOriginal: true,
    demoSrc: "https://moh-sa.dev",
    repoSrc: "https://github.com/moh-sa/Portfolio",
    imgSrc: portfolio,
    imgAlt: "",
    skills: [s.next, s.tailwind, s.og, s.ts],
  },
  {
    title: "King's Revenge",
    description:
      "A platformer game with hit-box and collision detection built entirely with vanilla JavaScript.",
    year: 2023,
    demoSrc: "https://kings-revenge.moh-sa.dev",
    repoSrc: "https://github.com/moh-sa/Kings-Revenge",
    imgSrc: platformer,
    imgAlt: "",
    skills: [s.js],
  },
  {
    title: "Globe",
    description: "An interactive globe created with Three.js and GASP.",
    year: 2023,
    demoSrc: "https://globe-threejs.moh-sa.dev/",
    repoSrc: "https://github.com/moh-sa/globe_threejs",
    imgSrc: globe,
    imgAlt: "",
    skills: [s.three, s.gasp],
  },
  {
    title: "Apple-like Store",
    description:
      "A Next.js eCommerce project that took inspiration from Apple stores. The project takes advantage of Sanity CMS to manage product information, Stripe to provide seamless credit card payments, and TailwindCSS for styles.",
    year: 2022,
    demoSrc: "https://apple-store.moh-sa.dev",
    repoSrc: "https://github.com/moh-sa/Apple-Store",
    imgSrc: appleStore,
    imgAlt: "",
    skills: [s.next, s.sanity, s.stripe, s.tailwind, s.ts],
  },
  {
    title: "proShop",
    description:
      "A React and Express.js eCommerce project with reviews and rating features and an admin page to handle all products, orders, and payments. Registration via email and JWT tokens for authentication Stores data with MongoDB and PayPal SDK for effortless payments.",
    year: 2022,
    demoSrc: "https://proshop.moh-sa.dev",
    repoSrc: "https://github.com/moh-sa/proShop",
    imgSrc: proShop,
    imgAlt: "",
    skills: [
      s.react,
      s.express,
      s.mongo,
      s.mongoose,
      s.paypal,
      s.redux,
      s.axios,
      s.react_router,
      s.jwt,
      s.bcrypt,
      s.multer,
    ],
  },
  {
    title: "Memories",
    description:
      "'Memories' is my first MERN personal project. The project utilized React.js for the front-end and Express.js for the back-end. To ensure security, Access and refresh JWT tokens were implemented for authentication, and account activation was done through email to ensure security.",
    year: 2022,
    isOriginal: true,
    demoSrc: "https://memories.moh-sa.dev",
    repoSrc: "https://github.com/moh-sa/memories",
    imgSrc: memories,
    imgAlt: "",
    skills: [
      s.react,
      s.express,
      s.mongo,
      s.mongoose,
      s.jwt,
      s.rtk,
      s.react_router,
      s.hookForm,
      s.axios,
      s.bcrypt,
      s.uuid,
      s.cloudinary,
      s.mantine,
    ],
  },
  {
    title: "Auto-Correction Smart Examination System",
    description:
      "Graduation project built with Oracle APEX. This system is based on the randomization of questions and variable answers generated by the system to prevent cheating.",
    year: 2021,
    isOriginal: true,
    imgSrc: autoCorrection,
    imgAlt: "",
    skills: [s.oracle_db, s.oracle_apex, s.bootstrap],
  },
];
